### PR TITLE
Line buffer utility and shell provisioner usage

### LINKED ISSUE #11047: Shell provisioner output all messed up
### Vagrant version
Vagrant 2.2.5

### Host operating system
Ubuntu 18.04.3 LTS

### Guest operating system
Ubuntu 18.04.3 LTS

### Vagrantfile

You just need to add a normal `config.vm.provision` step, e.g.:

```ruby
config.vm.provision 'shell', path: 'provision-kubernetes-master.sh'
```

The full Vagranfile is at https://github.com/rgl/kubernetes-ubuntu-vagrant/blob/master/Vagrantfile.

### Expected behavior
```
==> km1: NAME                                                                   AGE
==> km1: admin                                                                  48m
==> km1: cluster-admin                                                          48m
==> km1: edit                                                                   48m
==> km1: kube-router                                                            48m
==> km1: kubernetes-dashboard                                                   48m
==> km1: system:aggregate-to-admin                                              48m
==> km1: system:aggregate-to-edit                                               48m
==> km1: system:aggregate-to-view                                               48m
==> km1: system:auth-delegator                                                  48m
==> km1: system:basic-user                                                      48m
==> km1: system:certificates.k8s.io:certificatesigningrequests:nodeclient       48m
==> km1: system:certificates.k8s.io:certificatesigningrequests:selfnodeclient   48m
==> km1: system:controller:attachdetach-controller                              48m
==> km1: system:controller:certificate-controller                               48m
==> km1: system:controller:clusterrole-aggregation-controller                   48m
==> km1: system:controller:cronjob-controller                                   48m
==> km1: system:controller:daemon-set-controller                                48m
==> km1: system:controller:deployment-controller                                48m
==> km1: system:controller:disruption-controller                                48m
```

### Actual behavior
The output is all messed up, it seems that vagrant is not correctly interpreting the new lines or just dumps the whole output buffer when its full without regarding whether its tail has a new line or not, and thus, forces a new line. At least it seems that what is happening by looking at the garbled/messed output (the output should be two perfect columns of text like displayed in the Expected behavior section):

```
==> km1: NAME                                                                   AGE
==> km1: admin                                                                
==> km1:   48m
==> km1: cluster-admin                                                          48m
==> km1: edit                                                                   48m
==> km1: kube-router                                
==> km1:                             48m
==> km1: kubernetes-dashboard                                                   48m
==> km1: system:aggregate-to-admin                                              48m
==> km1: system:aggregate-to-edit                                               48m
==> km1: system:aggregate-to-view                                               48m
==> km1: system:auth-delegator                                                  48m
==> km1: system:basic-user                                                      48m
==> km1: system:certificates.k8s.io:certificatesigningrequests:nodeclient       48m
==> km1: system:certificates.k8s.io:certificatesigningrequests:selfnodeclient   48m
==> km1: system:controller:attachdetach-controller                              48m
==> km1: system:controller:certificate-controller                               48m
==> km1: system:controller:clusterrole-aggregation-controller                   48m
==> km1: system:controller:cronjob-controller                
==> km1:                    48m
==> km1: system:controller:daemon-set-controller                                48m
==> km1: system:controller:deployment-controller                                48m
==> km1: system:controller:disruption-controller                        
==> km1:         48m
```

This behavior practically makes the vagrant output useless and really hard to interpret.

### Steps to reproduce

This can be easily reproducible with the execute plugin:

1. `vagrant plugin install vagrant-execute`
2. `vagrant execute -c 'kubectl get clusterrole --all-namespaces' km1`

Or by launching the whole environment with `vagrant up`.

### PR DESCRIPTION
**Pull request by chrisroberts**
This is an extension of #12403. It's a slight refactor to remove the inclusion
of the StringIO library and to provide a max length for buffering to prevent
a badly behaving provisioner from consuming excess amounts of memory on the
host. Test coverage has also been included.

Thanks @rgl! This changeset also includes a rebase of main and I didn't want
to force push onto your branch so I opened a new PR instead.

Fixes #12403
Fixes #11047

### CODE REVIEW

**Comment by rgl** [comment]
@chrisroberts looking good! I particularly like how the Proc stuff is now better tamed :-)

File: lib/vagrant/util/line_buffer.rb [hunk 1]
```diff
@@ -0,0 +1,61 @@
...
+      # Closes the buffer. Any remaining data that has
+      # been buffered will be given to the callback.
+      # Once closed the instance will no longer be usable.
+      #
+      # @return [self]
+      def close
+        @mu.synchronize do
+          # Send any remaining output on the buffer
+          @callback.call(@buffer.dup) if
+            !@buffer.empty?
```
Comment (rgl) [inline lib/vagrant/util/line_buffer.rb:51]: Can this be replaced with `unless @buffer.empty?` in the same line as the callback call?

Comment (chrisroberts) [reply lib/vagrant/util/line_buffer.rb]: I pulled it up on the same line, but retained the `if !` instead of using `unless`. While there are instances of `unless` used in some of the Vagrant code, it's generally discouraged as `if` based conditions are easier to parse (for a person) the majority of the time, especially when there are compound statements.

**Review by soapy1 — APPROVED** [review]
