### PR TITLE
Exit 0 if vagrant destroy finds no running vms

### LINKED ISSUE #9137: vagrant destroy exits 1 when no running vm found
Please note that the Vagrant issue tracker is reserved for bug reports and
enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

### Vagrant version
Vagrant 2.0.1

### Host operating system
Windows 10

### Guest operating system
Centos/Windows2K12

### Expected behavior
Vagrant should exit 0 if attemting to destroy a vm that is not running.   This was the behaviour of destroy until 2.0.1

### Actual behavior
vagrant now exits 1 of no running vm found

### Steps to reproduce
$ vagrant destroy k8s_node
==> k8s_node: VM not created. Moving on...
$ echo $?
1

### PR DESCRIPTION
**Pull request by briancain**
This commit reverts the behavior of `vagrant destroy` to exit 0 if no
running vms were found when the destroy command is run.

Fixes #9137

### CODE REVIEW

File: plugins/commands/destroy/command.rb [hunk 1]
```diff
@@ -60,6 +60,11 @@ def execute
         # Nothing was declined
         return 0 if declined == 0
 
+        # Everything was declined, and all states are `not_created`
+        return 0 if declined == machines.length &&
+                    init_states.values.first == :not_created &&
+                    init_states.values.uniq.length == 1
```
Comment (chrisroberts) [inline plugins/commands/destroy/command.rb]: This conditional can be slimmed down:

```ruby
if declined == machines.size && declined == init_states.count(:not_created)
```

**Comment by briancain** [comment]
@chrisroberts - updated based on feedback!
