### PR TITLE
Guest support for OpenWrt

### LINKED ISSUE #11790: Guest operating system detection error
Vagrant is unable to detect the openwrt ARM virtual machine as linux. 

### Vagrant version

Vagrant Version:   Vagrant 2.2.9

### Host operating system

Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal

### Guest operating system
Vagrant-openwrt box: vladimir-babichev/openwrt-19.07.3
https://github.com/vladimir-babichev/vagrant-openwrt-box

### Vagrantfile

```ruby
Vagrant.configure("2") do |config|
  # Use OpenWRT 19.07.3 Vagrant box 
  config.vm.box = "vladimir-babichev/openwrt-19.07.3"
  config.vm.hostname = "openwrt"
end
```

### Debug output

$ vagrant halt
==> default: Attempting graceful shutdown of VM...
    default: 
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
The guest operating system of the machine could not be detected!
Vagrant requires this knowledge to perform specific tasks such
as mounting shared folders and configuring networks. Please add
the ability to detect this guest operating system to Vagrant
by creating a plugin or reporting a bug.

### Expected behavior

Vagrant produces the error on startup, provision and hat. 

### Actual behavior

What actually happened?

### Steps to reproduce

1. Create the a minimal vagrantfile with box vladimir-babichev/openwrt-19.07.3
2. Do 'vargant up'
3. Do 'vargrant halt'

### References
https://github.com/vladimir-babichev/vagrant-openwrt-box/issues/2

### PR DESCRIPTION
**Pull request by jbonhag**
This commit includes the following capabilities for OpenWrt:

- Guest detection
- SSH key replacement
- Change host name
- Synced folder support with rsync

Interesting things about OpenWrt:

- root login
- Default shell is ash
- Uses Busybox binaries
- Package manager is `opkg`

PR can be tested with the `vladimir-babichev/openwrt-19.07.3` box. Closes #11790.

### CODE REVIEW

**Comment by arky** [comment]
Thanks @jbonhag for a quick patch! Much appreciated.

File: plugins/guests/openwrt/guest.rb [hunk 1]
```diff
@@ -0,0 +1,10 @@
+require_relative '../linux/guest'
+
+module VagrantPlugins
+  module GuestOpenWrt
+    class Guest < VagrantPlugins::GuestLinux::Guest
+      # Name used for guest detection
+      GUEST_DETECTION_NAME = "openwrt".freeze
```
Comment (soapy1) [inline plugins/guests/openwrt/guest.rb:7]: for some older versions of openwrt, for example ntrepid8/openwrt-15.05-x86, guest detection fails since they don't have `/etc/os-release`. [OpenWrt docs](https://openwrt.org/docs/guide-user/installation/after.installation#what_version_of_openwrt_do_i_have_installed) suggests checking the version using a `cat /etc/banner` . This also seems to not work on older versions, but `uname -a` might be a good fallback. Or, maybe older versions of openwrt don't matter too much?

**Comment by arky** [comment]
@jbonhag @soapy1 Providing a more complete vagrantfile to facilitate testing.  

```ruby
Vagrant.configure("2") do |config|
  # Use OpenWRT 19.07.3 Vagrant box 
  config.vm.box = "vladimir-babichev/openwrt-19.07.3"
  config.vm.hostname = "openwrt"
  config.vm.post_up_message = "Please login using username 'root' and password 'vagrant' at http://openwrt.lan"

  config.vm.network "private_network", ip: "10.10.10.10"

  config.vm.provision "shell", inline: <<-SHELL
    opkg update 
    opkg install uhttpd-mod-ubus
    /etc/init.d/rpcd restart 
    /etc/init.d/uhttpd restart
  SHELL

end

```

File: plugins/guests/openwrt/guest.rb (hunk 1 above)
Comment (jbonhag) [reply plugins/guests/openwrt/guest.rb:7]: Whoa! 🙇 Thanks for that info. Some of the other guest plugins check a few different files to get the version, so I can do something similar here.

**Comment by jbonhag** [comment]
Thanks @soapy1 and @arky! I'll see about adding the network support.

**Comment by vladimir-babichev** [comment]
Hi guys,

This PR was open for a while now. Is there much work need to be done on the network side? Anything I or someone else can help you with? 

Cheers,
Vladimir

**Comment by soapy1** [comment]
@vladimir-babichev thanks for being interested in this! 
As far as I can tell so far, the PR is just missing the `configure_network` capability. Other guests have similar capabilities eg [darwin](https://github.com/hashicorp/vagrant/blob/master/plugins/guests/darwin/cap/configure_networks.rb) and [debian](https://github.com/hashicorp/vagrant/blob/master/plugins/guests/debian/cap/configure_networks.rb). If you are interested in getting this over the finish line, those might be good examples to follow.

**Comment by vladimir-babichev** [comment]
@soapy1 would you say `configure_network` capability is a prerequisit for this PR or it can be added later?
Never the less I'll try to help you out.

**Comment by soapy1** [comment]
@vladimir-babichev, ya I would say that the `configure_network` capability is a prereq for this PR

**Comment by arky** [comment]
Any update on this issues? it would be great if we could get his feature included in the next release. Thanks

**Review by soapy1 — APPROVED** [review]
I'm going to go ahead and merge this and open up an issue for the `configure_network` capability that needs to be added to enable the ability to set the ip of the guest. 🎆 🎆

**Comment by arky** [comment]
Thanks @soapy1 !
