### PR TITLE
Fixes #10741: Check if update is available locally

### LINKED ISSUE #10741: vagrant box outdated doesn't always check if the box is already available locally
If you have two Vagrant environments; update one, wait for an hour (or delete the box_update_check flag) and then try to check if the other one is outdated; you are incorrectly instructed to run `vagrant box update`, which fails.

The Steps to Reproduce section shows a more complete example, but to summarise:
- Create two Vagrant environments from the same base box
- Wait for the base box to be updated
- In the first environment, run `vagrant box outdated` and then follow the instructions to run `vagrant box update`
- Wait for an hour (or delete the box_update_check flag)
- In the second environment, run `vagrant box outdated` and then follow the instructions to run `vagrant box update`, which will fail

Instead at that last bullet point, Vagrant should give you a different message (see Expected Behavior).

I suspect the reason it doesn't is because https://github.com/hashicorp/vagrant/blob/master/lib/vagrant/action/builtin/box_check_outdated.rb#L81 only runs if `has_update?` (https://github.com/hashicorp/vagrant/blob/master/lib/vagrant/action/builtin/box_check_outdated.rb#L58) returns false. Which is also why the box_update_check flag matters, because if the flag is present and less than an hour old, `has_update?` returns false.

Finally this may seem an unusual set of circumstances to come across; but if you do your CI builds inside Vagrant environments and try to update the box on every run, it happens quite a lot!

### Vagrant version
Vagrant 2.2.4

### Host operating system
Ubuntu 16.04.6 LTS

### Guest operating system
Ubuntu 18.04.2 LTS

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-18.04"

end

```

### Debug output
https://gist.github.com/samdbmg/7644af22ccb9db416cae76e9317a2122

### Expected behavior
```console
samn:vagrant-example-2$ vagrant box outdated
Checking if box 'bento/ubuntu-18.04' version '201812.15.0' is up to date...
A newer version of the box 'bento/ubuntu-18.04' is available and already
installed, but your Vagrant machine is running against
version '201812.15.0'. To update to version '201812.27.0',
destroy and recreate your machine.
```

### Actual behavior
```console
samn:vagrant-example-2$ vagrant box outdated
Checking if box 'bento/ubuntu-18.04' version '201812.15.0' is up to date...
A newer version of the box 'bento/ubuntu-18.04' for provider 'virtualbox' is
available! You currently have version '201812.15.0'. The latest is version
'201812.27.0'. Run `vagrant box update` to update.
samn:vagrant-example-2$ vagrant box update
==> default: Checking for updates to 'bento/ubuntu-18.04'
    default: Latest installed version: 201812.15.0
    default: Version constraints: 
    default: Provider: virtualbox
==> default: Updating 'bento/ubuntu-18.04' with provider 'virtualbox' from version
==> default: '201812.15.0' to '201812.27.0'...
==> default: Loading metadata for box 'https://vagrantcloud.com/bento/ubuntu-18.04'
==> default: Adding box 'bento/ubuntu-18.04' (v201812.27.0) for provider: virtualbox
The box you're attempting to add already exists. Remove it before
adding it again or add it with the `--force` flag.

Name: bento/ubuntu-18.04
Provider: virtualbox
Version: 201812.27.0
```
### Steps to reproduce
```console
samn:vagrant-example$ vagrant box add bento/ubuntu-18.04 --box-version 201812.15.0  # Get an older version so there's a upgrade available; latest is 201812.27.0
<snip>
samn:vagrant-example$ vagrant up && vagrant halt
<snip>
samn:vagrant-example$ cd ../vagrant-example-2  # Same Vagrantfile
samn:vagrant-example-2$ vagrant up && vagrant halt
<snip>
samn:vagrant-example-2$ cd ../vagrant-example
samn:vagrant-example$ rm ~/.vagrant.d/boxes/bento-VAGRANTSLASH-ubuntu-18.04/201812.15.0/virtualbox/box_update_check  # Remove box_update_check; you could also just wait an hour for it to expire
samn:vagrant-example$ vagrant box outdated
Checking if box 'bento/ubuntu-18.04' version '201812.15.0' is up to date...
A newer version of the box 'bento/ubuntu-18.04' for provider 'virtualbox' is
available! You currently have version '201812.15.0'. The latest is version
'201812.27.0'. Run `vagrant box update` to update.
samn:vagrant-example$ vagrant box update
==> default: Checking for updates to 'bento/ubuntu-18.04'
    default: Latest installed version: 201812.15.0
    default: Version constraints: 
    default: Provider: virtualbox
==> default: Updating 'bento/ubuntu-18.04' with provider 'virtualbox' from version
==> default: '201812.15.0' to '201812.27.0'...
<snip>
samn:vagrant-example$ cd ../vagrant-example-2
samn:vagrant-example-2$ rm ~/.vagrant.d/boxes/bento-VAGRANTSLASH-ubuntu-18.04/201812.15.0/virtualbox/box_update_check 
```
Then as in Actual Behavior.

### PR DESCRIPTION
**Pull request by jbonhag**
Check the local box collection to see if the latest box update has already been downloaded.  If it has, don't show the "run vagrant update" message.

### CODE REVIEW

File: lib/vagrant/action/builtin/box_check_outdated.rb [hunk 1]
```diff
@@ -70,15 +70,23 @@ def call(env)
               message: e.message))
           end
           env[:box_outdated] = update != nil
-          if update
+          local_update = check_outdated_local(env)
+          if update and (local_update.nil? or local_update.version < update[1].version)
```
Comment (chrisroberts) [inline lib/vagrant/action/builtin/box_check_outdated.rb]: Please use `&&` and `||` instead of `and` and `or` to keep consistency
