### PR TITLE
Update docker provisioner for windows, fix command filter behavior for `rm`

### LINKED ISSUE #9280: Windows docker capability missing
### Guest operating system
Windows

### Vagrantfile
```ruby
config.vm.define "api" do |api|
    api.vm.box = "StefanScherer/windows_2016_docker"
    api.vm.box_version = "2017.12.14"
    api.vm.provision "docker" do |d|
    end
  end
```
### Expected behavior
Expect docker provisioning to work on windows

### Actual behavior
Capability is missing to detect if daemon is running

### Steps to reproduce
1. use above vagrantfile snippit

### LINKED ISSUE #9339: usage of "rm -f" is not portable
https://github.com/hashicorp/vagrant/blob/9c299a2a357fcf87f356bb9d56e18a037a53d138/plugins/provisioners/docker/client.rb#L131

Parameter cannot be processed because the parameter name 'f' is ambiguous. Possible matches include: -Filter -Force.

### PR DESCRIPTION
**Pull request by briancain**
This commit rebases #9353. It introduces a windows capability for the docker provisioner to check of the docker daemon is running. It also fixes the behavior of the `rm` filter for winrm. `rm -f dir` on linux does not result in an error, thus the winrm filter was updated since `rm`'ing a directory that doesn't exist on windows is an error.

Fixes #9339
Fixes #9280

### CODE REVIEW

File: plugins/communicators/winrm/command_filters/rm.rb [hunk 1]
```diff
@@ -31,9 +31,9 @@ def filter(command)
 
           ret_cmd = ''
           if recurse
-            ret_cmd = "rm \"#{dir}\" -recurse -force"
+            ret_cmd = "if (Test-Path #{dir}) {Remove-Item #{dir} -force -recurse}"
```
Comment (chrisroberts) [inline plugins/communicators/winrm/command_filters/rm.rb]: The `#{dir}`s need to be quoted

File: plugins/provisioners/docker/client.rb [hunk 2]
```diff
@@ -127,12 +127,9 @@ def container_args_changed?(config)
       def create_container(config)
         args = container_run_args(config)
 
-        @machine.communicate.sudo %[
-          rm -f #{config[:cidfile]}
-          docker run #{args}
-        ]
+        @machine.communicate.sudo %[rm -f #{config[:cidfile]}]
```
Comment (chrisroberts) [inline plugins/provisioners/docker/client.rb]: cidfile needs to be quoted
