### PR TITLE
Fix graceful_halt_timeout issue #8486

### LINKED ISSUE #8486: changing the a windows hostname takes forever when graceful_halt_timeout is set
### Vagrant version
1.9.2

### Host operating system
Windows 10

### Guest operating system
Windows Server 2016

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
    config.vm.box = "windows-2016-amd64"
    config.vm.define "windows-domain-controller"
    config.vm.hostname = "dc"
    config.vm.graceful_halt_timeout = 60*60 # 60 minutes.
    ...
```

### Debug output
It keeps stuck at:
```
INFO subprocess: Command not in installer, restoring original environment...                                                                                            
INFO winrmshell: Attempting to connect to WinRM...                                                                                                                      
INFO winrmshell:   - Host: 127.0.0.1                                                                                                                                    
INFO winrmshell:   - Port: 2200                                                                                                                                         
INFO winrmshell:   - Username: vagrant                                                                                                                                  
INFO winrmshell:   - Transport: plaintext                                                                                                                               
INFO winrm: WinRM is ready!                                                                                                                                             
INFO guest: Execute capability: change_host_name [#<Vagrant::Machine: windows-domain-controller (VagrantPlugins::ProviderVirtualBox::Provider)>, "dc"] (windows)        
```

### Expected behavior
The hostname change should be quick. In fact, when I login into the machine, the hostname is already changed; so, it seems that only an explicit reboot is needed.

### Actual behavior
It takes forever to change.

### PR DESCRIPTION
**Pull request by ajpaul25**
The current code waits for the entire value of machine.config.vm.graceful_halt_timeout when rebooting due to a hostname change.  This is not the intended use of this configuration parameter.  Graceful_halt_timeout is the amount of time to wait for a machine to respond to a graceful halt request before forcefully halting.  This change removes machine.config.vm.graceful_halt_timeout for the module in favor of using the existing wait_for_reboot code, thereby correcting issue #8486.

Fixes #8486

### CODE REVIEW

File: plugins/guests/windows/cap/change_host_name.rb [hunk 1]
```diff
@@ -28,7 +28,9 @@ def self.change_host_name_and_wait(machine, name, sleep_timeout)
             error_key: :rename_computer_failed)
 
           # Don't continue until the machine has shutdown and rebooted
-          sleep(sleep_timeout)
+	  if machine.guest.capability?(:wait_for_reboot)
+            machine.guest.capability(:wait_for_reboot)
+	  end
```
Comment (briancain) [inline plugins/guests/windows/cap/change_host_name.rb]: We should have an else clause here and just sleep. Perhaps leave the `sleep_timeout` param passed in and use that to fall back on?

File: plugins/guests/windows/cap/change_host_name.rb [hunk 2]
```diff
@@ -28,7 +28,9 @@ def self.change_host_name_and_wait(machine, name, sleep_timeout)
             error_key: :rename_computer_failed)
 
           # Don't continue until the machine has shutdown and rebooted
-          sleep(sleep_timeout)
+	  if machine.guest.capability?(:wait_for_reboot)
+            machine.guest.capability(:wait_for_reboot)
```
Comment (briancain) [inline plugins/guests/windows/cap/change_host_name.rb]: These two lines are the reasons for your rspec failures. You need to `allow` the machine double to be able to receive both `guest`, and the two functions `capability?` and `capability`.

**Comment by ajpaul25** [comment]
Thanks!  I've made the code changes, tested with rake and pushed.  Hopefully travis will be happy too.
