### PR TITLE
Always force string type conversion of path

### LINKED ISSUE #9984: vagrant (2.1.2) crashes if used with WSL and hyper-v provider
### Vagrant version
2.1.2

### Host operating system
Windows 10 (1803) / WSL (Ubuntu 16.04)

config for WSL (besides installed vagrant)
```
export VAGRANT_WSL_ENABLE_WINDOWS_ACCESS="1"
export PATH="$HOME/bin:$HOME/.local/bin:$PATH"
export PATH="$PATH:/mnt/c/Program\ Files/Docker/Docker/resources/bin"
export VAGRANT_DEFAULT_PROVIDER=hyperv
alias docker=docker.exe
alias docker-compose=docker-compose.exe
```

### Guest operating system
any

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.provider "hyperv" do |h|
    h.vm_integration_services = {
      guest_service_interface: true,
      CustomVMSRV: true
    }
  end  
end
```

### Debug output
```
vagrant up

Bringing machine 'default' up with 'hyperv' provider...
==> default: Verifying Hyper-V is enabled...
/opt/vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/util/platform.rb:395:in `wsl_to_windows_path': undefined method `match' for #<Pathname:0x000000000333a538> (NoMethodError)
        from /opt/vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/plugins/providers/hyperv/driver.rb:224:in `execute_powershell'
        from /opt/vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/plugins/providers/hyperv/driver.rb:47:in `execute'
        from /opt/vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/plugins/providers/hyperv/action/check_enabled.rb:15:in `call'
        from /opt/vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/action/builder.rb:116:in `call'
        from /opt/vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/action/runner.rb:66:in `block in run'
        from /opt/vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/util/busy.rb:19:in `busy'
        from /opt/vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/action/runner.rb:66:in `run'
        from /opt/vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/machine.rb:239:in `action_raw'
        from /opt/vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/machine.rb:208:in `block in action'
        from /opt/vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/environment.rb:598:in `lock'
        from /opt/vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/machine.rb:194:in `call'
        from /opt/vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/machine.rb:194:in `action'
        from /opt/vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
```

### Expected behavior
bringing up the guest

### Actual behavior
see above. i just receive that error message

### Steps to reproduce
1. Install latest vagrant 
2. enable hyper-V as default provider (or use --provider=hyperv)
3. add user to hyper-v administrator group at Host OS
3. change into folder with vagrant file and try a vagrant up

### PR DESCRIPTION
**Pull request by chrisroberts**
Fixes #9984

### CODE REVIEW

File: lib/vagrant/util/platform.rb [hunk 1]
```diff
@@ -405,7 +406,7 @@ def wsl_to_windows_path(path)
               end
               path = [root_path, *parts].join("\\")
             else
-              path = path.to_s.sub("/mnt/", "")
+              path = path.sub("/mnt/", "")
```
Comment (briancain) [inline lib/vagrant/util/platform.rb]: Can `path.to_s` at the bottom of this method be just `path` now with this change?

Comment (chrisroberts) [reply lib/vagrant/util/platform.rb]: Yep!
