### PR TITLE
VirtualBox hostnet addressing

### LINKED ISSUE #12996: private_network vagrant up error
### Debug output

==> default: Importing base box 'bento/debian-10'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'bento/debian-10' version '202206.03.0' is up to date...
==> default: Setting the name of the VM: test_default_1668574693400_31170
==> default: Clearing any previously set network interfaces...
==> default: Destroying VM and associated drives...
Traceback (most recent call last):
        125: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/lib/vagrant/batch_action.rb:86:in `block (2 levels) in run'
        124: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/lib/vagrant/machine.rb:203:in `action'
        123: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/lib/vagrant/machine.rb:203:in `call'
        122: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/lib/vagrant/environment.rb:631:in `lock'
        121: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/lib/vagrant/machine.rb:217:in `block in action'
        120: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/lib/vagrant/machine.rb:248:in `action_raw'
        119: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/lib/vagrant/action/runner.rb:101:in `run'
        118: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/lib/vagrant/util/busy.rb:19:in `busy'
        117: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/lib/vagrant/action/runner.rb:101:in `block in run'
        116: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/lib/vagrant/action/builder.rb:180:in `call'
        115: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/lib/vagrant/action/warden.rb:48:in `call'
        114: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/plugins/providers/virtualbox/action/check_virtualbox.rb:26:in `call'
        113: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/lib/vagrant/action/warden.rb:48:in `call'
        112: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/lib/vagrant/action/builtin/call.rb:53:in `call'
        111: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/lib/vagrant/action/runner.rb:101:in `run'
        110: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/lib/vagrant/util/busy.rb:19:in `busy'
        109: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/lib/vagrant/action/runner.rb:101:in `block in run'
        108: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/lib/vagrant/action/builder.rb:180:in `call'
        107: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/lib/vagrant/action/warden.rb:48:in `call'
        106: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
        105: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/lib/vagrant/action/warden.rb:48:in `call'
        104: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/lib/vagrant/action/builtin/handle_box.rb:56:in `call'
        103: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/lib/vagrant/action/warden.rb:48:in `call'
        102: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
        101: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/lib/vagrant/action/warden.rb:48:in `call'
        100: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
         99: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/lib/vagrant/action/warden.rb:48:in `call'
         98: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/lib/vagrant/action/builtin/call.rb:53:in `call'
         97: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/lib/vagrant/action/runner.rb:101:in `run'
         96: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/lib/vagrant/util/busy.rb:19:in `busy'
         95: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/lib/vagrant/action/runner.rb:101:in `block in run'
         94: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/lib/vagrant/action/builder.rb:180:in `call'
         93: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/lib/vagrant/action/warden.rb:48:in `call'
         92: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
         91: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/lib/vagrant/action/warden.rb:48:in `call'
         90: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/plugins/providers/virtualbox/action/check_accessible.rb:18:in `call'
         89: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/lib/vagrant/action/warden.rb:48:in `call'
         88: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/plugins/providers/virtualbox/action/customize.rb:40:in `call'
         87: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/lib/vagrant/action/warden.rb:48:in `call'
         86: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/lib/vagrant/action/builtin/prepare_clone.rb:15:in `call'
         85: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/lib/vagrant/action/warden.rb:48:in `call'
         84: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/plugins/providers/virtualbox/action/prepare_clone_snapshot.rb:17:in `call'
         83: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/lib/vagrant/action/warden.rb:48:in `call'
         82: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/plugins/providers/virtualbox/action/import.rb:13:in `call'
         81: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/plugins/providers/virtualbox/action/import.rb:78:in `import'
         80: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/lib/vagrant/action/warden.rb:48:in `call'
         79: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/plugins/providers/virtualbox/action/discard_state.rb:15:in `call'
         78: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/lib/vagrant/action/warden.rb:48:in `call'
         77: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/plugins/providers/virtualbox/action/match_mac_address.rb:22:in `call'
         76: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/lib/vagrant/action/warden.rb:48:in `call'
         75: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
         74: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/lib/vagrant/action/warden.rb:48:in `call'
         73: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/lib/vagrant/action/builtin/env_set.rb:19:in `call'
         72: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/lib/vagrant/action/warden.rb:48:in `call'
         71: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/plugins/providers/virtualbox/action/check_virtualbox.rb:26:in `call'
         70: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/lib/vagrant/action/warden.rb:48:in `call'
         69: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
         68: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/lib/vagrant/action/warden.rb:48:in `call'
         67: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/lib/vagrant/action/builtin/box_check_outdated.rb:93:in `call'
         66: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/lib/vagrant/action/warden.rb:48:in `call'
         65: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/lib/vagrant/action/builtin/call.rb:53:in `call'
         64: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/lib/vagrant/action/runner.rb:101:in `run'
         63: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/lib/vagrant/util/busy.rb:19:in `busy'
         62: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/lib/vagrant/action/runner.rb:101:in `block in run'
         61: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/lib/vagrant/action/builder.rb:180:in `call'
         60: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/lib/vagrant/action/warden.rb:48:in `call'
         59: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
         58: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/lib/vagrant/action/warden.rb:48:in `call'
         57: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/lib/vagrant/action/builtin/call.rb:53:in `call'
         56: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/lib/vagrant/action/runner.rb:101:in `run'
         55: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/lib/vagrant/util/busy.rb:19:in `busy'
         54: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/lib/vagrant/action/runner.rb:101:in `block in run'
         53: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/lib/vagrant/action/builder.rb:180:in `call'
         52: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/lib/vagrant/action/warden.rb:48:in `call'
         51: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
         50: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/lib/vagrant/action/warden.rb:48:in `call'
         49: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/lib/vagrant/action/builtin/call.rb:53:in `call'
         48: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/lib/vagrant/action/runner.rb:101:in `run'
         47: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/lib/vagrant/util/busy.rb:19:in `busy'
         46: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/lib/vagrant/action/runner.rb:101:in `block in run'
         45: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/lib/vagrant/action/builder.rb:180:in `call'
         44: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/lib/vagrant/action/warden.rb:48:in `call'
         43: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
         42: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/lib/vagrant/action/warden.rb:48:in `call'
         41: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/plugins/providers/virtualbox/action/check_accessible.rb:18:in `call'
         40: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/lib/vagrant/action/warden.rb:48:in `call'
         39: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/plugins/providers/virtualbox/action/clean_machine_folder.rb:26:in `call'
         38: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/lib/vagrant/action/warden.rb:48:in `call'
         37: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/plugins/providers/virtualbox/action/set_name.rb:50:in `call'
         36: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/lib/vagrant/action/warden.rb:48:in `call'
         35: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/plugins/providers/virtualbox/action/clear_forwarded_ports.rb:15:in `call'
         34: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/lib/vagrant/action/warden.rb:48:in `call'
         33: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/lib/vagrant/action/builtin/provision.rb:80:in `call'
         32: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/lib/vagrant/action/warden.rb:48:in `call'
         31: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/lib/vagrant/action/builtin/env_set.rb:19:in `call'
         30: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/lib/vagrant/action/warden.rb:48:in `call'
         29: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/plugins/providers/virtualbox/action/prepare_forwarded_port_collision_params.rb:30:in `call'
         28: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/lib/vagrant/action/warden.rb:48:in `call'
         27: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/lib/vagrant/action/builtin/handle_forwarded_port_collisions.rb:52:in `call'
         26: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/lib/vagrant/action/warden.rb:48:in `call'
         25: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/plugins/providers/virtualbox/action/prepare_nfs_valid_ids.rb:12:in `call'
         24: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/lib/vagrant/action/warden.rb:48:in `call'
         23: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/plugins/synced_folders/nfs/action_cleanup.rb:25:in `call'
         22: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/lib/vagrant/action/warden.rb:48:in `call'
         21: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/lib/vagrant/action/builtin/synced_folder_cleanup.rb:28:in `call'
         20: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/lib/vagrant/action/warden.rb:48:in `call'
         19: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/lib/vagrant/action/builtin/delayed.rb:19:in `call'
         18: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/lib/vagrant/action/warden.rb:48:in `call'
         17: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/lib/vagrant/action/builtin/synced_folders.rb:87:in `call'
         16: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/lib/vagrant/action/warden.rb:48:in `call'
         15: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/plugins/providers/virtualbox/action/prepare_nfs_settings.rb:19:in `call'
         14: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/lib/vagrant/action/warden.rb:48:in `call'
         13: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/plugins/providers/virtualbox/action/set_default_nic_type.rb:64:in `call'
         12: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/lib/vagrant/action/warden.rb:48:in `call'
         11: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/plugins/providers/virtualbox/action/clear_network_interfaces.rb:26:in `call'
         10: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/lib/vagrant/action/warden.rb:48:in `call'
          9: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/plugins/providers/virtualbox/action/network.rb:94:in `call'
          8: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/plugins/providers/virtualbox/action/network.rb:94:in `each'
          7: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/plugins/providers/virtualbox/action/network.rb:101:in `block in call'
          6: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/plugins/providers/virtualbox/action/network.rb:311:in `hostonly_config'
          5: from /opt/vagrant/embedded/lib/ruby/2.7.0/forwardable.rb:235:in `read_bridged_interfaces'
          4: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/plugins/providers/virtualbox/driver/version_7_0.rb:32:in `read_bridged_interfaces'
          3: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/plugins/providers/virtualbox/driver/version_7_0.rb:32:in `delete_if'
          2: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/plugins/providers/virtualbox/driver/version_7_0.rb:33:in `block in read_bridged_interfaces'
          1: from /opt/vagrant/embedded/gems/2.3.3/gems/vagrant-2.3.3/plugins/providers/virtualbox/driver/version_7_0.rb:33:in `new'
/opt/vagrant/embedded/gems/2.3.3/gems/ipaddr-1.2.4/lib/ipaddr.rb:594:in `initialize': address family must be specified (IPAddr::AddressFamilyError)

### Expected behavior

vm up

### Actual behavior

vagrant up error

#### Vagrant version

2.3.3

#### Host operating system

macos 10.15.7

#### Guest operating system

bento/debian-10

#### Steps to reproduce

1. add config.vm.network "private_network", ip: "192.168.56.10"
2. vagrant up
3. error

#### Vagrantfile

```ruby
# Copy-paste your Vagrantfile here. Remove any sensitive information such as passwords, authentication tokens, or email addresses.
```

Vagrant.configure("2") do |config|
  config.vm.box = "bento/debian-10"
  config.vm.network "private_network", ip: "192.168.56.10"
end

### PR DESCRIPTION
**Pull request by chrisroberts**
Rescue any address errors logging them and ignoring the address. Update
how the host address is determined based on the network configuration.
Host address will be either the lowest address assignable via dhcp
configuration or first address available within the configured subnet.

Fixes #12996

### CODE REVIEW

File: plugins/providers/virtualbox/driver/version_7_0.rb [hunk 1]
```diff
@@ -107,7 +113,8 @@ def create_host_only_network(options)
             opts[:upper] = options[:dhcp_upper]
           else
             addr = IPAddr.new(options[:adapter_ip])
-            opts[:upper] = opts[:lower] = addr.mask(opts[:netmask]).to_range.first.to_s
+            opts[:upper] = opts[:lower] =
+            addr.mask(opts[:netmask]).to_range.first.to_s
```
Comment (phinze) [inline plugins/providers/virtualbox/driver/version_7_0.rb:117]: Nit: Looks like this might be an accidental newline addition

File: plugins/providers/virtualbox/driver/version_7_0.rb [hunk 2]
```diff
@@ -30,8 +30,14 @@ def read_bridged_interfaces
 
           # Prune any hostonly interfaces in the list
           ifaces.delete_if { |i|
-            addr = IPAddr.new(i[:ip]).mask(i[:netmask])
-            hostonly_ifaces.include?(addr)
+            addr = begin
+                     IPAddr.new(i[:ip]).mask(i[:netmask])
+                   rescue IPAddr::Error => err
+                     @logger.debug("skipping bridged interface due to parse error #{err} (#{i}) ")
```
Comment (phinze) [inline plugins/providers/virtualbox/driver/version_7_0.rb:36]: Nit: I think this probably warrants a `.warn`

**Review by phinze — APPROVED** [review]
Looks good! Two optional inline nite
