### PR TITLE
Vagrant is unable to execute Get-WindowsOptionalFeature Command #11932

### LINKED ISSUE #11932: Vagrant is unable to execute Get-WindowsOptionalFeature Command
### Vagrant version

Vagrant 2.2.9

### Host operating system

Windows

### Guest operating system

Ubuntu/bionic 18.04

### Vagrantfile

```ruby

Vagrant.configure("2") do |config|
 
  config.vm.box = "ubuntu/bionic64"
  config.vm.hostname = "ubuntubase"

  config.vm.box_check_update = false

  

  config.vm.network "forwarded_port", guest: 80, host: 8050

  config.vm.network "private_network", ip: "192.168.33.10"

 
  config.vm.synced_folder "./data", "/vagrant_data"


  config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
    vb.gui = false
  #
  #   # Customize the amount of memory on the VM:
    vb.memory = "5000"
    vb.cpus = 2
  end

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y apt-transport-https ca-certificates curl gnupg-agent software-properties-common
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
    apt-key fingerprint 0EBFCD88
    add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
    apt-get update
    apt-get install -y docker-ce docker-ce-cli containerd.io
  SHELL
end

```

Please ensure the Vagrantfile provided is a minimal Vagrantfile which contains
only the required configuration to reproduce the behavior. Please note that if
your Vagrantfile contains an excess of configuration unrelated the the reported
issue, or is in a different format, we may be unable to assist with your issue.
Always start with a minimal Vagrantfile and include only the relevant configuration
to reproduce the reported behavior.

### Debug output

https://gist.github.com/lyderX05/bb8e27c169916db5dece818fcbe1c963

### Expected behavior

During Debug it should resolve the get windows Microsoft hyper-v information.

### Actual behavior

Unable to get the details and showing below error:
```powershell
 INFO subprocess: Starting process: ["C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\/powershell.EXE", "-NoLogo", "-NoProfile", "-NonInteractive", "-ExecutionPolicy", 
"Bypass", "-Command", "$(Get-WindowsOptionalFeature -FeatureName Microsoft-Hyper-V-Hypervisor).State"]

 INFO subprocess: Command not in installer, restoring original environment...

DEBUG subprocess: Selecting on IO

DEBUG subprocess: stderr: Get-WindowsOptionalFeature : Parameter set cannot be resolved using the specified named parameters.
At line:1 char:3
+ $(Get-WindowsOptionalFeature -FeatureName Microsoft-Hyper-V-Hyperviso ...
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-WindowsOptionalFeature], ParameterBindingException
    + FullyQualifiedErrorId : AmbiguousParameterSet,Microsoft.Dism.Commands.GetWindowsOptionalFeatureCommand
 

DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 31999

DEBUG subprocess: Exit status: 0

 INFO subprocess: Starting process: ["C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\/powershell.EXE", "-NoLogo", "-NoProfile", "-NonInteractive", "-ExecutionPolicy", 
"Bypass", "-Command", "$(Get-WindowsFeature -FeatureName Microsoft-Hyper-V-Hypervisor).State"]

 INFO subprocess: Command not in installer, restoring original environment...

DEBUG subprocess: Selecting on IO

DEBUG subprocess: stderr: Get-WindowsFeature : The term 'Get-WindowsFeature' is not recognized as the name of a cmdlet, function, script file, or operable program. Check 
the spelling of the name, 
or if a path was included, verify that the path is correct and try again.
At line:1 char:3
+ $(Get-WindowsFeature -FeatureName Microsoft-Hyper-V-Hypervisor).State
+   ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-WindowsFeature:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```
### Steps to reproduce

1. Install vagrant on windows OS
2. Run any vagrantfile, configure with basic configuration
3. Debug the output you will see the result.

### PR DESCRIPTION
**Pull request by lyderX05**
Fixes the background issue where the vagrant failing where Get-WindowsFeature command is not available. 

Fixes #11932

### CODE REVIEW

**Review by soapy1 — DISMISSED** [review]

File: lib/vagrant/util/platform.rb [hunk 1]
```diff
@@ -139,8 +139,12 @@ def windows_hyperv_enabled?
           return @_windows_hyperv_enabled if defined?(@_windows_hyperv_enabled)
 
           @_windows_hyperv_enabled = -> {
-            ["Get-WindowsOptionalFeature", "Get-WindowsFeature"].each do |cmd_name|
-              ps_cmd = "$(#{cmd_name} -FeatureName Microsoft-Hyper-V-Hypervisor).State"
+            {:"Get-WindowsOptionalFeature" => ["-Online"], :"Get-WindowsFeature" => []}.each do |cmd_name, arguments|
+              parameters = arguments.join " "
+              ps_cmd = "$(#{cmd_name} -FeatureName Microsoft-Hyper-V-Hypervisor #{parameters}).State"
+              if cmd_name == "Get-WindowsFeature"
```
Comment (soapy1) [inline lib/vagrant/util/platform.rb:145]: I don't think this part is required since a failure is handled by `Vagrant::Util::PowerShell.execute_cmd`

**Review by chrisroberts — CHANGES_REQUESTED** [review]
Hi there, thanks for this PR. I think that with the differences in the commands, we should build each command string fully, then create a new array with them and loop. It will reduce some of the complexity and make things a little clearer:

```ruby
check_commands = Array.new.tap do |c|
  c << "Get-WindowsOptionalFeature ..."
  c << "Get-WindowsFeature ..."
end
check_commands.each do |ps_cmd|
  ...
```

The conditional added won't be needed as we are only checking for the expected `Enabled` value, so any other output isn't required.

Thanks!

File: lib/vagrant/util/platform.rb (hunk 1 above)
Comment (lyderX05) [reply lib/vagrant/util/platform.rb:145]: Would it be required if HVM Microsoft HVM installed or not, if installed it should fail the vagrant because of that

**Comment by lyderX05** [comment]
Updated As per Requested Changes.

File: lib/vagrant/util/platform.rb (hunk 1 above)
Comment (soapy1) [reply lib/vagrant/util/platform.rb]: Ya, if it fails it shouldn't raise an error. This is the [code for the powershell execute_cmd](https://github.com/hashicorp/vagrant/blob/master/lib/vagrant/util/powershell.rb#L116). It returns `nil` if the return code is not 0. Testing this theory out (with a little bit of an extreme example). For a diff like

```
diff --git a/lib/vagrant/util/platform.rb b/lib/vagrant/util/platform.rb
index 1d8e32119..57146031f 100644
--- a/lib/vagrant/util/platform.rb
+++ b/lib/vagrant/util/platform.rb
@@ -142,6 +142,7 @@ module Vagrant
             check_commands = Array.new.tap do |c|
               c << "(Get-WindowsOptionalFeature -FeatureName Microsoft-Hyper-V-Hypervisor -Online).State"
               c << "(Get-WindowsFeature -FeatureName Microsoft-Hyper-V-Hypervisor).State"
+              c << "(SOMETHING BROKEN).state"
             end
``` 

Vagrant does the correct thing.

**Comment by soapy1** [comment]
Heya, sorry for taking so long to get back to this. These changes look good! Just rebased on main to get the tests to run and we'll get this merged in 🎆

**Review by soapy1 — APPROVED** [review]

**Review by phinze — APPROVED** [review]
