### PR TITLE
Store box metadata of active guest

### LINKED ISSUE #9884: Can't update box after specifying version
`vagrant up --no-provision` was nagging me:

```
==> default: A newer version of the box 'ubuntu/bionic64' for provider 'virtualbox' is
==> default: available! You currently have version '20180517.0.0'. The latest is version
==> default: '20180529.0.0'. Run `vagrant box update` to update.
```

To avoid this error and ensure that all users have the same Vagrant box, I tried setting it in the Vagrantfile, after which `vagrant box update` failed unexpectedly and `vagrant up --no-provision` silently ignores the outdated version.

### Vagrant version

2.1.1

### Host operating system

Arch Linux (up to date as of today, 2018-05-30).

### Guest operating system

ubuntu/bionic64

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.box_version = "20180529.0.0"
  config.vm.provision "shell", inline: "sudo /vagrant/provisioning/vagrant/provision.sh"
  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "provisioning/ansible/setup-development-vm.yml"
  end
  config.vm.network "forwarded_port", guest: 80, host: 8000
  config.vm.network "forwarded_port", guest: 8080, host: 8080
end
```

### Expected behavior

1. `vagrant box update` should update the box.
1. `vagrant up --no-provision && vagrant provision` should **either** advise the user to update the box **or** update the box automatically before provisioning.

### Actual behavior

```
$ vagrant box update
==> default: Box 'ubuntu/bionic64' not installed, can't check for updates.
```

`vagrant up --no-provision && vagrant provision` prints no warning and does not update the box.

### Steps to reproduce
1. Spin up a "ubuntu/bionic64" box with no version specified
1. Specify a box version as above
1. Either
   1. run `vagrant box update` or
   1. run `vagrant up --no-provision && vagrant provision`

### PR DESCRIPTION
**Pull request by chrisroberts**
When a guest is created, the box metadata information is stored in the
machine data directory. This allows modifications to happen to the
Vagrantfile definition of the box in use (box name change, box version
change, etc) while still allowing the Machine instance of an active
guest successfully load the box currently backing it.

Fixes #9884

### CODE REVIEW

File: lib/vagrant/vagrantfile.rb [hunk 1]
```diff
@@ -170,6 +170,19 @@ def machine_config(name, provider, boxes)
...
+      # Check if this machine has a local box metadata file
+      # describing the existing guest. If so, load it and
+      # set the box name and version to allow the actual
+      # box in use to be discovered.
+      if data_path
+        meta_file = data_path.join("box_meta")
+        if meta_file.file?
+          box_meta = JSON.parse(meta_file.read)
+          config.vm.box = box_meta["name"]
+          config.vm.box_version = box_meta["box_version"]
```
Comment (briancain) [inline lib/vagrant/vagrantfile.rb]: I think this should be:

```ruby
config.vm.box_version = box_meta["version"]
```

It looks like it's stored as `version`
