### PR TITLE
Fix --output path with specified folder

### LINKED ISSUE #9088: vagrant package silently fails when --output path contains a slash
### Vagrant version

```console
$ vagrant -v
Vagrant 2.0.0
```

### Host operating system

macOS Sierra

### Guest operating system

erickoegel/dfly48

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "erickoegel/dfly48"
  config.vm.provision "shell", path: "bootstrap.sh"
end
```

### bootstrap.sh

```sh
#!/bin/sh
sudo pkg update && \
    sudo pkg install -y rsync
```

### Expected behavior

Ideally, Vagrant checks to see if a `mcandre` directory exists. If not, Vagrant creates the directory and writes a `dragonfly-rsync.box` file inside the directory.

Or, Vagrant exits with a non-zero status and warns the user that the path would be invalid.

### Actual behavior

Vagrant takes several minutes to produce a box, then I have no idea where the box ends up, because no *.box files are produced.

### Steps to reproduce
1. `vagrant up`
2. `vagrant package --output mcandre/dragonfly-rsync.box`

As a workaround, I am careful to `--output` to `dragonfly-rsync.box`, and then import the box as `mcandre/dragonfly-rsync` to my vagrant box list.

### PR DESCRIPTION
**Pull request by bpietraga**
This pull request is in to resolve ticket

Fixes #9088

### CODE REVIEW

File: lib/vagrant/action/general/package.rb [hunk 1]
```diff
@@ -72,6 +72,7 @@ def call(env)
           @env = env
 
           self.class.validate!(env["package.output"], env["package.directory"])
+          package_with_folder_path(fullpath) if output_inside_folder?(env)
```
Comment (briancain) [inline lib/vagrant/action/general/package.rb]: Is this variable different from `@fullpath`? And if not...I think it can be accessed within that function without being passed in as a parameter.

File: lib/vagrant/action/general/package.rb [hunk 2]
```diff
@@ -83,6 +84,20 @@ def call(env)
           compress
         end
 
+        def output_inside_folder?(env)
+          env["package.output"].include?('/')
```
[the remark this answers is not in the document]
Comment (briancain) [reply lib/vagrant/action/general/package.rb]: Also, can we just use `@fullpath` here, I think? If we can just use the variable, I don't know if it needs to be a function.

File: lib/vagrant/action/general/package.rb [hunk 3]
```diff
@@ -83,6 +84,20 @@ def call(env)
...
+        end
+
+        def package_with_folder_path(fullpath)
+          folder_path = File.expand_path('../', fullpath)
```
Comment (briancain) [inline lib/vagrant/action/general/package.rb]: I think this can just be `File.expand_path('..', fullpath)` so that it works on windows.

File: lib/vagrant/action/general/package.rb (hunk 2 above)
[the remark this answers is not in the document]
Comment (bpietraga) [reply lib/vagrant/action/general/package.rb]: `env["package.output"]` returns `"mcandre/dragonfly-rsync.box"`
`@fullpath`returns `"/Users/bpietraga/mcandre/dragonfly-rsync.box"`

File: lib/vagrant/action/general/package.rb (hunk 1 above)
Comment (bpietraga) [reply lib/vagrant/action/general/package.rb]: Thanks! :) I agree. A bit over 80 lines way to go then:

```ruby
package_with_folder_path if env["package.output"].include?(File::SEPARATOR)
```

**Comment by bpietraga** [comment]
@briancain Thank you for extensive code review. 🙂 
I submitted changes to the commit addressing things you found and wrote test for this functionality.
Also I've removed the WIP from commit name and PR.
