### PR TITLE
Smb symlinks

### LINKED ISSUE #8854: Allow symbolic links in samba shares by default
### Vagrant version
1.9.7

### Host operating system
Windows 10 x64

### Guest operating system
Ubuntu x64

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/trusty64"

    config.vm.network "private_network", ip: "192.168.33.70"
    config.vm.synced_folder ".", "/vagrant"
    config.vm.synced_folder ".", "/opt/foo", type: "smb"
```

### Steps to reproduce
1. `vagrant up && vagrant ssh`
2. `cd /opt/foo`
3. `touch foo`
4. `ln -s foo bar`

### Expected behavior
A `bar` symbolic link is created

### Actual behavior
```
$ ln -s foo bar
ln: failed to create symbolic link ‘bar’: Operation not supported
```

### More info
Symbolic links can be created on samba shares, if they are mounted with the `mfsymlinks` mount option (more info [here](https://wiki.samba.org/index.php/UNIX_Extensions#Minshall.2BFrench_symlinks)). I'm not aware of any downsides of having this option be enabled by default. I.e. it'd be great to have it being enabled [here](https://github.com/mitchellh/vagrant/blob/98b0ad1/plugins/guests/linux/cap/mount_smb_shared_folder.rb#L27)
```ruby
          options[:mount_options] ||= []
          options[:mount_options] << "sec=ntlm"
          options[:mount_options] << "mfsymlinks"
          options[:mount_options] << "credentials=/etc/smb_creds_#{name}"
```

This would make one more thing to work out of the box, as many webdev frameworks use symlinks in one way or another.

Thank you.

### PR DESCRIPTION
**Pull request by soapy1**
fixes #8854

### CODE REVIEW

File: test/unit/plugins/guests/linux/cap/mount_smb_shared_folder.rb [hunk 1]
```diff
@@ -44,6 +44,8 @@
       allow(comm).to receive(:execute).with(any_args)
       allow(machine).to receive(:guest).and_return(guest)
       allow(guest).to receive(:capability).with(:shell_expand_guest_path, mount_guest_path).and_return(mount_guest_path)
+      allow(ENV).to receive(:[]).and_return(false)
```
Comment (chrisroberts) [inline test/unit/plugins/guests/linux/cap/mount_smb_shared_folder.rb:47]: Should include a `with` on this to restrict matching (`allow(ENV).to receive(:[]).with("VAGRANT_DISABLE_SMBMFSYMLINKS").and_return(false)`)

File: test/unit/plugins/guests/linux/cap/mount_smb_shared_folder.rb [hunk 2]
```diff
@@ -76,6 +78,17 @@
       cap.mount_smb_shared_folder(machine, mount_name, mount_guest_path, folder_options)
     end
 
+    it "it adds mfsymlinks option by default" do
```
Comment (chrisroberts) [inline test/unit/plugins/guests/linux/cap/mount_smb_shared_folder.rb:81]: Remove extraneous `it` within string

File: test/unit/plugins/guests/linux/cap/mount_smb_shared_folder.rb [hunk 3]
```diff
@@ -76,6 +78,17 @@
...
+      expect(comm).to receive(:sudo).with(/mfsymlinks/, any_args)
+      cap.mount_smb_shared_folder(machine, mount_name, mount_guest_path, folder_options)
+    end
+
+    it "t does not add mfsymlinks option if env var VAGRANT_DISABLE_SMBMFSYMLINKS exists" do
```
Comment (chrisroberts) [inline test/unit/plugins/guests/linux/cap/mount_smb_shared_folder.rb:86]: Remove `t ` in string

File: test/unit/plugins/guests/linux/cap/mount_smb_shared_folder.rb [hunk 4]
```diff
@@ -76,6 +78,17 @@
...
+      allow(ENV).to receive(:[]).with("VAGRANT_DISABLE_SMBMFSYMLINKS").and_return(true)
```
Comment (chrisroberts) [inline test/unit/plugins/guests/linux/cap/mount_smb_shared_folder.rb:87]: Update the `allow(ENV)` to be `expect(ENV)`

File: plugins/guests/linux/cap/mount_smb_shared_folder.rb [hunk 5]
```diff
@@ -34,10 +35,17 @@ def self.mount_smb_shared_folder(machine, name, guestpath, options)
...
           mnt_opts << "uid=#{mount_uid}"
           mnt_opts << "gid=#{mount_gid}"
+          if !ENV['VAGRANT_DISABLE_SMBMFSYMLINKS']
+            mnt_opts << "mfsymlinks"
+          end
 
           mnt_opts = merge_mount_options(mnt_opts, options[:mount_options] || [])
 
           mount_options = "-o #{mnt_opts.join(",")}"
+          if mount_options.include? "mfsymlinks"
```
Comment (chrisroberts) [inline plugins/guests/linux/cap/mount_smb_shared_folder.rb:45]: Would you please add parens on the method: `mount_options.include?("mfsymlinks")`
